#!/bin/sh
set -e

ITER=./iter-cli

"$ITER" 0 -1 >iter.out <<IN
1
2
3
IN
diff -u iter.out - <<OUT
1
2
3
OUT

"$ITER" 2 4 >iter.out <<IN
1
2
3
4
5
IN
diff -u iter.out - <<OUT
2
3
4
OUT

"$ITER" 0 -1 >iter.out <<IN
1
1
IN
diff -u iter.out - <<OUT
dupe: 1
1
OUT

"$ITER" 0 -1 >iter.out <<IN
16
32
48
64
128
IN
diff -u iter.out - <<OUT
16
32
48
64
128
OUT

"$ITER" 33 127 >iter.out <<IN
16
32
48
64
128
IN
diff -u iter.out - <<OUT
48
64
OUT

"$ITER" 0 -1 >iter.out <<IN
16
17
32
33
48
49
64
65
128
129
IN
diff -u iter.out - <<OUT
16
17
32
33
48
49
64
65
128
129
OUT

"$ITER" 33 127 >iter.out <<IN
16
17
32
33
48
49
64
65
128
129
IN
diff -u iter.out - <<OUT
33
48
49
64
65
OUT
